server:
  port: 9527

spring:
  application:
    name: cloud-zuul-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

#配置微服务代理
zuul:
  #忽略真实的服务名，即不能使用服务名访问，只能通过代理访问以保证安全
  ignored-services: "*"
  routes:
    #指定要代理的微服务名称和路径
    cloud-consul-provider: /users/**

